{{- if .Values.opensearch.enabled }}
{{- if .Values.opensearch.ismPolicy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opensearch-ism-policy
data:
  policy.json: |
    {
      "policy": {
        "description": "Auto-delete logstash indexes after {{ .Values.opensearch.ismPolicy.retentionDays }} days",
        "default_state": "hot",
        "states": [
          {
            "name": "hot",
            "actions": [],
            "transitions": [
              {
                "state_name": "delete",
                "conditions": {
                  "min_index_age": "{{ .Values.opensearch.ismPolicy.retentionDays }}d"
                }
              }
            ]
          },
          {
            "name": "delete",
            "actions": [
              {
                "delete": {}
              }
            ],
            "transitions": []
          }
        ],
        "ism_template": [
          {
            "index_patterns": ["{{ .Values.opensearch.ismPolicy.indexPattern }}"],
            "priority": 100
          }
        ]
      }
    }
{{- end }}
{{- end }}
