{{- if .Values.opensearch.enabled }}
{{- if .Values.opensearch.dashboards.enabled }}
{{- if .Values.opensearch.savedSearch.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opensearch-saved-search
data:
  saved-search.ndjson: |
{{ .Files.Get "dashboards/saved-search.ndjson" | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
