{{- if and (index .Values "keycloak-init" "enabled") (index .Values "keycloak-init" "keycloak" "password") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "keycloak-init" "keycloak" "existingSecret" }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{ index .Values "keycloak-init" "keycloak" "existingSecretKey" }}: {{ index .Values "keycloak-init" "keycloak" "password" | quote }}
{{- end }}
