{{- if .Values.minio.enabled }}
{{- $secretName := include "common.names.fullname" .Subcharts.minio }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.minio.commonLabels "context" .Subcharts.minio) | nindent 4 }}
  {{- if .Values.minio.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.minio.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  root-user: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "root-user" "providedValues" (list "auth.rootUser") "length" 10 "strong" false "context" .Subcharts.minio) }}
  root-password: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "root-password" "providedValues" (list "auth.rootPassword") "length" 16 "strong" false "context" .Subcharts.minio) }}
  {{- if .Values.minio.readOnlyUser.enabled }}
  readonly-user: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "readonly-user" "providedValues" (list "readOnlyUser.accessKey") "length" 16 "strong" false "failOnNew" "false" "context" .Subcharts.minio) }}
  readonly-password: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "readonly-password" "providedValues" (list "readOnlyUser.secretKey") "length" 32 "strong" false "failOnNew" "false" "context" .Subcharts.minio) }}
  {{- end }}
{{- end }}
